@url=http://localhost:3005/v1
@tokenAdmin=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyOTUzMTYzNX0.1ghsSyObEJgju8XitfLZJ3y9FmNmCsGwJFuVTOpkaFs
@tokenUser= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyLCJlbWFpbCI6InVzZXJAZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2Mjk1MzE2Nzl9.NyXzIb4EyLf2yac_Q631_4xPSIO-1M0nTLm5RVN8_F0

###########################
########## USERS ##########
###########################

########## LOGIN ##########
post {{url}}/users/login
Content-Type: application/json

{
"email": "admin@gmail.com",
"password": "Password1234!"
}

######## REGISTER #########
post {{url}}/users/register
Authorization: {{tokenAdmin}}
Content-Type: application/json

{
"name": "Federico",
"lastname": "García",
"email": "userdsfg@gmail.com",
"password": "Pasword1234!",
"role": "user"
}

######## GET ALL USERS #########
get {{url}}/users/
Authorization: {{tokenAdmin}}

######## GET USER #########
get {{url}}/users/1
Authorization: {{tokenAdmin}}

######## UPDATE USER #########
put {{url}}/users/2
Authorization: {{tokenAdmin}}
Content-Type: application/json

{
"name": "Daniel",
"lastname": "Gaía",
"email": "user@gmail.com",
"password": "Pasword1234!",
"role": "USER"
}

######## DELETE USER #########
delete {{url}}/users/40
Authorization: {{tokenAdmin}}

###########################
######### CONTACTS ########
###########################

######## GET ALL CONTACTS #########
get {{url}}/contacts/
Authorization: {{tokenUser}}

######## GET CONTACT #########
get {{url}}/contacts/1
Authorization: {{tokenUser}}

######## CREATE CONTACT #########
post {{url}}/contacts/
Authorization: {{tokenUser}}
Content-Type: application/json

{
  "name": "Julio",
  "lastname": "Cortazar",
  "email": "juliocortazarasd@gmail.com",
  "address": "Calle sin Nombre 10",
  "phone": "9999999999999",
  "preference_phone": 2,
  "linkedin": "juliocortazar",
  "preference_linkedin": 3,
  "facebook": "juliocortazar",
  "preference_facebook": 1,
  "twitter": "juliocortazar",
  "preference_twitter": 1,
  "instagram": "juliocortazar",
  "preference_instagram": 1,
  "position": "Gerente",
  "interest": 100,
  "id_company": 1,
  "id_city": 1
}
######## UPDATE CONTACT #########
put {{url}}/contacts/24
Authorization: {{tokenUser}}
Content-Type: application/json

{
  "name": "Julisdfo",
  "lastname": "Cortazar",
  "email": "juliocortazar@gmail.com",
  "address": "Calle sin Nombre 10",
  "phone": "9999999999999",
  "preference_phone": 2,
  "linkedin": "juliocortazar",
  "preference_linkedin": 3,
  "facebook": "juliocortazar",
  "preference_facebook": 1,
  "twitter": "juliocortazar",
  "preference_twitter": 1,
  "instagram": "juliocortazar",
  "preference_instagram": 1,
  "position": "Gerente",
  "interest": 100,
  "id_company": 1,
  "id_city": 1
}
######## DELETE CONTACT #########
delete {{url}}/contacts/13
Authorization: {{tokenUser}}

############################
######### COMPANIES ########
############################

######## GET ALL COMPANIES #########
get {{url}}/companies/
Authorization: {{tokenUser}}

######## GET COMPANIY #########
get {{url}}/companies/3
Authorization: {{tokenUser}}

######## CREATE COMPANY #########
post {{url}}/companies
Authorization: {{tokenUser}}
Content-Type: application/json

{
  "name": "COMPAÑIA X",
  "email": "algo@gmail.com",
  "phone": "8888888888888",
  "address": "Calle sin Nomnre 99",
  "id_city": 5
}

######## UPDATE COMPANY #########
put {{url}}/companies/10
Authorization: {{tokenUser}}
Content-Type: application/json

{
  "name": "COMPAÑIA Y",
  "email": "algo@gmail.comy",
  "phone": "8888888888888Y",
  "address": "Calle sin Nomnre YY",
  "id_city": 7
}

######## DELETE COMPANY #########
delete {{url}}/companies/99
Authorization: {{tokenUser}}

##########################
######### REGIONS ########
##########################

######## GET ALL REGIONS #########
get {{url}}/regions
Authorization: {{tokenUser}}

######## GET REGION #########
get {{url}}/regions/1
Authorization: {{tokenUser}}

######## CREATE REGION #########
post {{url}}/regions
Authorization: {{tokenUser}}
Content-Type: application/json

{
  "name": "Europa"
}

######## UPDATE REGION #########
put {{url}}/regions/4
Authorization: {{tokenUser}}
Content-Type: application/json

{
  "name": "Africa"
}

######## DELETE REGION #########
delete {{url}}/regions/4
Authorization: {{tokenUser}}

############################
######### COUNTRIES ########
############################

######## GET ALL COUNTRIES #########
get {{url}}/countries/
Authorization: {{tokenUser}}

######## GET REGION #########
get {{url}}/countries/1
Authorization: {{tokenUser}}

######## CREATE REGION #########
post {{url}}/countries
Authorization: {{tokenUser}}
Content-Type: application/json

{
  "name": "Chile",
  "id_region": 3
}

######## UPDATE REGION #########
put {{url}}/countries/5
Authorization: {{tokenUser}}
Content-Type: application/json

{
  "name": "Chilecito",
  "id_region": 3
}

######## DELETE REGION #########
delete {{url}}/countries/5
Authorization: {{tokenUser}}

############################
########## CITIES ##########
############################

######## GET ALL CITIES #########
get {{url}}/cities/
Authorization: {{tokenUser}}

######## GET CITY #########
get {{url}}/cities/1
Authorization: {{tokenUser}}

######## CREATE REGION #########
post {{url}}/cities
Authorization: {{tokenUser}}
Content-Type: application/json

{
  "name": "Tijuana",
  "id_country": 1
}

######## UPDATE REGION #########
put {{url}}/cities/10
Authorization: {{tokenUser}}
Content-Type: application/json

{
  "name": "Chilecito",
  "id_country": 3
}

######## DELETE REGION #########
delete {{url}}/cities/10
Authorization: {{tokenUser}}

######## VERIF TOKEN  #########
get {{url}}/others/verifytoken/
Authorization: {{tokenUser}}

####
get {{url}}/preferences